# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luisf/repos/data-structure-and-algorithm-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luisf/repos/data-structure-and-algorithm-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luisf/repos/data-structure-and-algorithm-cpp/CMakeFiles /home/luisf/repos/data-structure-and-algorithm-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luisf/repos/data-structure-and-algorithm-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named data_structure_and_algorithm_cpp_lib

# Build rule for target.
data_structure_and_algorithm_cpp_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data_structure_and_algorithm_cpp_lib
.PHONY : data_structure_and_algorithm_cpp_lib

# fast build rule for target.
data_structure_and_algorithm_cpp_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp_lib.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp_lib.dir/build
.PHONY : data_structure_and_algorithm_cpp_lib/fast

#=============================================================================
# Target rules for targets named data_structure_and_algorithm_cpp

# Build rule for target.
data_structure_and_algorithm_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data_structure_and_algorithm_cpp
.PHONY : data_structure_and_algorithm_cpp

# fast build rule for target.
data_structure_and_algorithm_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp.dir/build
.PHONY : data_structure_and_algorithm_cpp/fast

#=============================================================================
# Target rules for targets named project_ArrayList

# Build rule for target.
project_ArrayList: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_ArrayList
.PHONY : project_ArrayList

# fast build rule for target.
project_ArrayList/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayList.dir/build.make CMakeFiles/project_ArrayList.dir/build
.PHONY : project_ArrayList/fast

#=============================================================================
# Target rules for targets named project_ArrayStack

# Build rule for target.
project_ArrayStack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_ArrayStack
.PHONY : project_ArrayStack

# fast build rule for target.
project_ArrayStack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayStack.dir/build.make CMakeFiles/project_ArrayStack.dir/build
.PHONY : project_ArrayStack/fast

#=============================================================================
# Target rules for targets named project_BinarySearchTree

# Build rule for target.
project_BinarySearchTree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_BinarySearchTree
.PHONY : project_BinarySearchTree

# fast build rule for target.
project_BinarySearchTree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_BinarySearchTree.dir/build.make CMakeFiles/project_BinarySearchTree.dir/build
.PHONY : project_BinarySearchTree/fast

#=============================================================================
# Target rules for targets named project_DoublyLinkedList

# Build rule for target.
project_DoublyLinkedList: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_DoublyLinkedList
.PHONY : project_DoublyLinkedList

# fast build rule for target.
project_DoublyLinkedList/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_DoublyLinkedList.dir/build.make CMakeFiles/project_DoublyLinkedList.dir/build
.PHONY : project_DoublyLinkedList/fast

#=============================================================================
# Target rules for targets named project_Graph

# Build rule for target.
project_Graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_Graph
.PHONY : project_Graph

# fast build rule for target.
project_Graph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Graph.dir/build.make CMakeFiles/project_Graph.dir/build
.PHONY : project_Graph/fast

#=============================================================================
# Target rules for targets named project_Hashmap

# Build rule for target.
project_Hashmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_Hashmap
.PHONY : project_Hashmap

# fast build rule for target.
project_Hashmap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Hashmap.dir/build.make CMakeFiles/project_Hashmap.dir/build
.PHONY : project_Hashmap/fast

#=============================================================================
# Target rules for targets named project_LinkedList

# Build rule for target.
project_LinkedList: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_LinkedList
.PHONY : project_LinkedList

# fast build rule for target.
project_LinkedList/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedList.dir/build.make CMakeFiles/project_LinkedList.dir/build
.PHONY : project_LinkedList/fast

#=============================================================================
# Target rules for targets named project_LinkedQueue

# Build rule for target.
project_LinkedQueue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_LinkedQueue
.PHONY : project_LinkedQueue

# fast build rule for target.
project_LinkedQueue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedQueue.dir/build.make CMakeFiles/project_LinkedQueue.dir/build
.PHONY : project_LinkedQueue/fast

#=============================================================================
# Target rules for targets named project_Sorting

# Build rule for target.
project_Sorting: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_Sorting
.PHONY : project_Sorting

# fast build rule for target.
project_Sorting/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Sorting.dir/build.make CMakeFiles/project_Sorting.dir/build
.PHONY : project_Sorting/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/ArrayList.test.o: tests/ArrayList.test.cpp.o
.PHONY : tests/ArrayList.test.o

# target to build an object file
tests/ArrayList.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayList.dir/build.make CMakeFiles/project_ArrayList.dir/tests/ArrayList.test.cpp.o
.PHONY : tests/ArrayList.test.cpp.o

tests/ArrayList.test.i: tests/ArrayList.test.cpp.i
.PHONY : tests/ArrayList.test.i

# target to preprocess a source file
tests/ArrayList.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayList.dir/build.make CMakeFiles/project_ArrayList.dir/tests/ArrayList.test.cpp.i
.PHONY : tests/ArrayList.test.cpp.i

tests/ArrayList.test.s: tests/ArrayList.test.cpp.s
.PHONY : tests/ArrayList.test.s

# target to generate assembly for a file
tests/ArrayList.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayList.dir/build.make CMakeFiles/project_ArrayList.dir/tests/ArrayList.test.cpp.s
.PHONY : tests/ArrayList.test.cpp.s

tests/ArrayStack.test.o: tests/ArrayStack.test.cpp.o
.PHONY : tests/ArrayStack.test.o

# target to build an object file
tests/ArrayStack.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayStack.dir/build.make CMakeFiles/project_ArrayStack.dir/tests/ArrayStack.test.cpp.o
.PHONY : tests/ArrayStack.test.cpp.o

tests/ArrayStack.test.i: tests/ArrayStack.test.cpp.i
.PHONY : tests/ArrayStack.test.i

# target to preprocess a source file
tests/ArrayStack.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayStack.dir/build.make CMakeFiles/project_ArrayStack.dir/tests/ArrayStack.test.cpp.i
.PHONY : tests/ArrayStack.test.cpp.i

tests/ArrayStack.test.s: tests/ArrayStack.test.cpp.s
.PHONY : tests/ArrayStack.test.s

# target to generate assembly for a file
tests/ArrayStack.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayStack.dir/build.make CMakeFiles/project_ArrayStack.dir/tests/ArrayStack.test.cpp.s
.PHONY : tests/ArrayStack.test.cpp.s

tests/BinarySearchTree.test.o: tests/BinarySearchTree.test.cpp.o
.PHONY : tests/BinarySearchTree.test.o

# target to build an object file
tests/BinarySearchTree.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_BinarySearchTree.dir/build.make CMakeFiles/project_BinarySearchTree.dir/tests/BinarySearchTree.test.cpp.o
.PHONY : tests/BinarySearchTree.test.cpp.o

tests/BinarySearchTree.test.i: tests/BinarySearchTree.test.cpp.i
.PHONY : tests/BinarySearchTree.test.i

# target to preprocess a source file
tests/BinarySearchTree.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_BinarySearchTree.dir/build.make CMakeFiles/project_BinarySearchTree.dir/tests/BinarySearchTree.test.cpp.i
.PHONY : tests/BinarySearchTree.test.cpp.i

tests/BinarySearchTree.test.s: tests/BinarySearchTree.test.cpp.s
.PHONY : tests/BinarySearchTree.test.s

# target to generate assembly for a file
tests/BinarySearchTree.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_BinarySearchTree.dir/build.make CMakeFiles/project_BinarySearchTree.dir/tests/BinarySearchTree.test.cpp.s
.PHONY : tests/BinarySearchTree.test.cpp.s

tests/DoublyLinkedList.test.o: tests/DoublyLinkedList.test.cpp.o
.PHONY : tests/DoublyLinkedList.test.o

# target to build an object file
tests/DoublyLinkedList.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_DoublyLinkedList.dir/build.make CMakeFiles/project_DoublyLinkedList.dir/tests/DoublyLinkedList.test.cpp.o
.PHONY : tests/DoublyLinkedList.test.cpp.o

tests/DoublyLinkedList.test.i: tests/DoublyLinkedList.test.cpp.i
.PHONY : tests/DoublyLinkedList.test.i

# target to preprocess a source file
tests/DoublyLinkedList.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_DoublyLinkedList.dir/build.make CMakeFiles/project_DoublyLinkedList.dir/tests/DoublyLinkedList.test.cpp.i
.PHONY : tests/DoublyLinkedList.test.cpp.i

tests/DoublyLinkedList.test.s: tests/DoublyLinkedList.test.cpp.s
.PHONY : tests/DoublyLinkedList.test.s

# target to generate assembly for a file
tests/DoublyLinkedList.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_DoublyLinkedList.dir/build.make CMakeFiles/project_DoublyLinkedList.dir/tests/DoublyLinkedList.test.cpp.s
.PHONY : tests/DoublyLinkedList.test.cpp.s

tests/Graph.test.o: tests/Graph.test.cpp.o
.PHONY : tests/Graph.test.o

# target to build an object file
tests/Graph.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Graph.dir/build.make CMakeFiles/project_Graph.dir/tests/Graph.test.cpp.o
.PHONY : tests/Graph.test.cpp.o

tests/Graph.test.i: tests/Graph.test.cpp.i
.PHONY : tests/Graph.test.i

# target to preprocess a source file
tests/Graph.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Graph.dir/build.make CMakeFiles/project_Graph.dir/tests/Graph.test.cpp.i
.PHONY : tests/Graph.test.cpp.i

tests/Graph.test.s: tests/Graph.test.cpp.s
.PHONY : tests/Graph.test.s

# target to generate assembly for a file
tests/Graph.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Graph.dir/build.make CMakeFiles/project_Graph.dir/tests/Graph.test.cpp.s
.PHONY : tests/Graph.test.cpp.s

tests/Hashmap.test.o: tests/Hashmap.test.cpp.o
.PHONY : tests/Hashmap.test.o

# target to build an object file
tests/Hashmap.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Hashmap.dir/build.make CMakeFiles/project_Hashmap.dir/tests/Hashmap.test.cpp.o
.PHONY : tests/Hashmap.test.cpp.o

tests/Hashmap.test.i: tests/Hashmap.test.cpp.i
.PHONY : tests/Hashmap.test.i

# target to preprocess a source file
tests/Hashmap.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Hashmap.dir/build.make CMakeFiles/project_Hashmap.dir/tests/Hashmap.test.cpp.i
.PHONY : tests/Hashmap.test.cpp.i

tests/Hashmap.test.s: tests/Hashmap.test.cpp.s
.PHONY : tests/Hashmap.test.s

# target to generate assembly for a file
tests/Hashmap.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Hashmap.dir/build.make CMakeFiles/project_Hashmap.dir/tests/Hashmap.test.cpp.s
.PHONY : tests/Hashmap.test.cpp.s

tests/LinkedList.test.o: tests/LinkedList.test.cpp.o
.PHONY : tests/LinkedList.test.o

# target to build an object file
tests/LinkedList.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedList.dir/build.make CMakeFiles/project_LinkedList.dir/tests/LinkedList.test.cpp.o
.PHONY : tests/LinkedList.test.cpp.o

tests/LinkedList.test.i: tests/LinkedList.test.cpp.i
.PHONY : tests/LinkedList.test.i

# target to preprocess a source file
tests/LinkedList.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedList.dir/build.make CMakeFiles/project_LinkedList.dir/tests/LinkedList.test.cpp.i
.PHONY : tests/LinkedList.test.cpp.i

tests/LinkedList.test.s: tests/LinkedList.test.cpp.s
.PHONY : tests/LinkedList.test.s

# target to generate assembly for a file
tests/LinkedList.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedList.dir/build.make CMakeFiles/project_LinkedList.dir/tests/LinkedList.test.cpp.s
.PHONY : tests/LinkedList.test.cpp.s

tests/LinkedQueue.test.o: tests/LinkedQueue.test.cpp.o
.PHONY : tests/LinkedQueue.test.o

# target to build an object file
tests/LinkedQueue.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedQueue.dir/build.make CMakeFiles/project_LinkedQueue.dir/tests/LinkedQueue.test.cpp.o
.PHONY : tests/LinkedQueue.test.cpp.o

tests/LinkedQueue.test.i: tests/LinkedQueue.test.cpp.i
.PHONY : tests/LinkedQueue.test.i

# target to preprocess a source file
tests/LinkedQueue.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedQueue.dir/build.make CMakeFiles/project_LinkedQueue.dir/tests/LinkedQueue.test.cpp.i
.PHONY : tests/LinkedQueue.test.cpp.i

tests/LinkedQueue.test.s: tests/LinkedQueue.test.cpp.s
.PHONY : tests/LinkedQueue.test.s

# target to generate assembly for a file
tests/LinkedQueue.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedQueue.dir/build.make CMakeFiles/project_LinkedQueue.dir/tests/LinkedQueue.test.cpp.s
.PHONY : tests/LinkedQueue.test.cpp.s

tests/Sorting.test.o: tests/Sorting.test.cpp.o
.PHONY : tests/Sorting.test.o

# target to build an object file
tests/Sorting.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Sorting.dir/build.make CMakeFiles/project_Sorting.dir/tests/Sorting.test.cpp.o
.PHONY : tests/Sorting.test.cpp.o

tests/Sorting.test.i: tests/Sorting.test.cpp.i
.PHONY : tests/Sorting.test.i

# target to preprocess a source file
tests/Sorting.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Sorting.dir/build.make CMakeFiles/project_Sorting.dir/tests/Sorting.test.cpp.i
.PHONY : tests/Sorting.test.cpp.i

tests/Sorting.test.s: tests/Sorting.test.cpp.s
.PHONY : tests/Sorting.test.s

# target to generate assembly for a file
tests/Sorting.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_Sorting.dir/build.make CMakeFiles/project_Sorting.dir/tests/Sorting.test.cpp.s
.PHONY : tests/Sorting.test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... data_structure_and_algorithm_cpp"
	@echo "... data_structure_and_algorithm_cpp_lib"
	@echo "... project_ArrayList"
	@echo "... project_ArrayStack"
	@echo "... project_BinarySearchTree"
	@echo "... project_DoublyLinkedList"
	@echo "... project_Graph"
	@echo "... project_Hashmap"
	@echo "... project_LinkedList"
	@echo "... project_LinkedQueue"
	@echo "... project_Sorting"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/ArrayList.test.o"
	@echo "... tests/ArrayList.test.i"
	@echo "... tests/ArrayList.test.s"
	@echo "... tests/ArrayStack.test.o"
	@echo "... tests/ArrayStack.test.i"
	@echo "... tests/ArrayStack.test.s"
	@echo "... tests/BinarySearchTree.test.o"
	@echo "... tests/BinarySearchTree.test.i"
	@echo "... tests/BinarySearchTree.test.s"
	@echo "... tests/DoublyLinkedList.test.o"
	@echo "... tests/DoublyLinkedList.test.i"
	@echo "... tests/DoublyLinkedList.test.s"
	@echo "... tests/Graph.test.o"
	@echo "... tests/Graph.test.i"
	@echo "... tests/Graph.test.s"
	@echo "... tests/Hashmap.test.o"
	@echo "... tests/Hashmap.test.i"
	@echo "... tests/Hashmap.test.s"
	@echo "... tests/LinkedList.test.o"
	@echo "... tests/LinkedList.test.i"
	@echo "... tests/LinkedList.test.s"
	@echo "... tests/LinkedQueue.test.o"
	@echo "... tests/LinkedQueue.test.i"
	@echo "... tests/LinkedQueue.test.s"
	@echo "... tests/Sorting.test.o"
	@echo "... tests/Sorting.test.i"
	@echo "... tests/Sorting.test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

