# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/htnek/Documentos/repos/data-structure-and-algorithm-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/htnek/Documentos/repos/data-structure-and-algorithm-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/htnek/Documentos/repos/data-structure-and-algorithm-cpp/CMakeFiles /home/htnek/Documentos/repos/data-structure-and-algorithm-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/htnek/Documentos/repos/data-structure-and-algorithm-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named data_structure_and_algorithm_cpp_lib

# Build rule for target.
data_structure_and_algorithm_cpp_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data_structure_and_algorithm_cpp_lib
.PHONY : data_structure_and_algorithm_cpp_lib

# fast build rule for target.
data_structure_and_algorithm_cpp_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp_lib.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp_lib.dir/build
.PHONY : data_structure_and_algorithm_cpp_lib/fast

#=============================================================================
# Target rules for targets named data_structure_and_algorithm_cpp

# Build rule for target.
data_structure_and_algorithm_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data_structure_and_algorithm_cpp
.PHONY : data_structure_and_algorithm_cpp

# fast build rule for target.
data_structure_and_algorithm_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp.dir/build
.PHONY : data_structure_and_algorithm_cpp/fast

#=============================================================================
# Target rules for targets named project_ArrayList

# Build rule for target.
project_ArrayList: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_ArrayList
.PHONY : project_ArrayList

# fast build rule for target.
project_ArrayList/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayList.dir/build.make CMakeFiles/project_ArrayList.dir/build
.PHONY : project_ArrayList/fast

#=============================================================================
# Target rules for targets named project_DoublyLinkedList

# Build rule for target.
project_DoublyLinkedList: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_DoublyLinkedList
.PHONY : project_DoublyLinkedList

# fast build rule for target.
project_DoublyLinkedList/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_DoublyLinkedList.dir/build.make CMakeFiles/project_DoublyLinkedList.dir/build
.PHONY : project_DoublyLinkedList/fast

#=============================================================================
# Target rules for targets named project_LinkedList

# Build rule for target.
project_LinkedList: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_LinkedList
.PHONY : project_LinkedList

# fast build rule for target.
project_LinkedList/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedList.dir/build.make CMakeFiles/project_LinkedList.dir/build
.PHONY : project_LinkedList/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/data_structure_and_algorithm_cpp.dir/build.make CMakeFiles/data_structure_and_algorithm_cpp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/ArrayList.test.o: tests/ArrayList.test.cpp.o
.PHONY : tests/ArrayList.test.o

# target to build an object file
tests/ArrayList.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayList.dir/build.make CMakeFiles/project_ArrayList.dir/tests/ArrayList.test.cpp.o
.PHONY : tests/ArrayList.test.cpp.o

tests/ArrayList.test.i: tests/ArrayList.test.cpp.i
.PHONY : tests/ArrayList.test.i

# target to preprocess a source file
tests/ArrayList.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayList.dir/build.make CMakeFiles/project_ArrayList.dir/tests/ArrayList.test.cpp.i
.PHONY : tests/ArrayList.test.cpp.i

tests/ArrayList.test.s: tests/ArrayList.test.cpp.s
.PHONY : tests/ArrayList.test.s

# target to generate assembly for a file
tests/ArrayList.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_ArrayList.dir/build.make CMakeFiles/project_ArrayList.dir/tests/ArrayList.test.cpp.s
.PHONY : tests/ArrayList.test.cpp.s

tests/DoublyLinkedList.test.o: tests/DoublyLinkedList.test.cpp.o
.PHONY : tests/DoublyLinkedList.test.o

# target to build an object file
tests/DoublyLinkedList.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_DoublyLinkedList.dir/build.make CMakeFiles/project_DoublyLinkedList.dir/tests/DoublyLinkedList.test.cpp.o
.PHONY : tests/DoublyLinkedList.test.cpp.o

tests/DoublyLinkedList.test.i: tests/DoublyLinkedList.test.cpp.i
.PHONY : tests/DoublyLinkedList.test.i

# target to preprocess a source file
tests/DoublyLinkedList.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_DoublyLinkedList.dir/build.make CMakeFiles/project_DoublyLinkedList.dir/tests/DoublyLinkedList.test.cpp.i
.PHONY : tests/DoublyLinkedList.test.cpp.i

tests/DoublyLinkedList.test.s: tests/DoublyLinkedList.test.cpp.s
.PHONY : tests/DoublyLinkedList.test.s

# target to generate assembly for a file
tests/DoublyLinkedList.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_DoublyLinkedList.dir/build.make CMakeFiles/project_DoublyLinkedList.dir/tests/DoublyLinkedList.test.cpp.s
.PHONY : tests/DoublyLinkedList.test.cpp.s

tests/LinkedList.test.o: tests/LinkedList.test.cpp.o
.PHONY : tests/LinkedList.test.o

# target to build an object file
tests/LinkedList.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedList.dir/build.make CMakeFiles/project_LinkedList.dir/tests/LinkedList.test.cpp.o
.PHONY : tests/LinkedList.test.cpp.o

tests/LinkedList.test.i: tests/LinkedList.test.cpp.i
.PHONY : tests/LinkedList.test.i

# target to preprocess a source file
tests/LinkedList.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedList.dir/build.make CMakeFiles/project_LinkedList.dir/tests/LinkedList.test.cpp.i
.PHONY : tests/LinkedList.test.cpp.i

tests/LinkedList.test.s: tests/LinkedList.test.cpp.s
.PHONY : tests/LinkedList.test.s

# target to generate assembly for a file
tests/LinkedList.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_LinkedList.dir/build.make CMakeFiles/project_LinkedList.dir/tests/LinkedList.test.cpp.s
.PHONY : tests/LinkedList.test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... data_structure_and_algorithm_cpp"
	@echo "... data_structure_and_algorithm_cpp_lib"
	@echo "... project_ArrayList"
	@echo "... project_DoublyLinkedList"
	@echo "... project_LinkedList"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/ArrayList.test.o"
	@echo "... tests/ArrayList.test.i"
	@echo "... tests/ArrayList.test.s"
	@echo "... tests/DoublyLinkedList.test.o"
	@echo "... tests/DoublyLinkedList.test.i"
	@echo "... tests/DoublyLinkedList.test.s"
	@echo "... tests/LinkedList.test.o"
	@echo "... tests/LinkedList.test.i"
	@echo "... tests/LinkedList.test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

